#!/usr/bin/env python3
"""Extract the per-column-count command layout from golden instruction streams.

Everything in a stream except one thing is a closed-form function of
(M, K, N, tiles, cols) -- see INSTS_FORMAT.md. The exception is which physical
shim column each buffer descriptor lands on and in what order, which is IRON's
placer output. That layout turns out to depend only on `cols`, so it can be
extracted once and compiled into sequence.cpp as a small table.

This script decodes chunk 0 of a golden, resolves every DDR offset into an
integer slot index against the shape-derived unit, and emits sequence_layout.h.

The goldens it reads must have at least two M-chunks (M >= 2*tileM*8), since
that is what exposes the alternating buffer-descriptor sets. The shipped grid is
compiled at one chunk, so compile dedicated ones first:

    gemm_bf16.compile_aot("npu2", cols, "bf16", 512, 512, 64*cols, 32, 64, 32, ...)

Run only when adding a new column count:
    python extract_layout.py --dir <golden dir> > ../sequence_layout.h
"""

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import parse_insts as P

ART = Path(__file__).parent.parent.parent / "cpp" / "external" / "ryzenai_artifacts"

# One golden per column count is enough: the layout was verified identical
# between npu1 and npu2 and between bf16 and bfp16, and every numeric field is
# recomputed from the shape, so only the placer's ordering is captured here.
COLUMN_COUNTS = [1, 2, 4, 8]
GOLDEN_M, GOLDEN_K = 512, 512
TILE_M, TILE_K, TILE_N = 32, 64, 32

AIE_ROWS = 4


def decode_cmds(path):
    return P.decode(P.u32s(Path(path).read_bytes()))[1][1:]


def chunk_starts(cmds, chunkCBytes):
    starts = []
    for i, l in enumerate(cmds):
        m = re.search(r"arg_idx=2 arg_off=(\d+)", l)
        if m and int(m.group(1)) % chunkCBytes == 0 and int(m.group(1)) // chunkCBytes == len(starts):
            starts.append(i - 1)  # the BLOCKWRITE precedes its DDR_PATCH
    starts.append(len(cmds))
    return starts


def field(line, pat, cast=int):
    m = re.search(pat, line)
    return cast(m.group(1)) if m else None


def extract(name, cols, path, M, K, N, tm, tk, tn):
    cmds = decode_cmds(path)
    chunkRows = tm * AIE_ROWS * 2
    chunkCBytes = chunkRows * N * 4
    starts = chunk_starts(cmds, chunkCBytes)
    if len(starts) < 3:
        raise SystemExit("%s: need a golden with at least 2 chunks" % name)

    # Units the DDR offsets are multiples of, derived from the shape.
    unitC = tn * 4                       # C strips advance one tile of float32
    unitA = chunkRows * K * 2 // (2 * cols)  # A slices split the chunk's rows
    unitB = tn * 4 // 2                  # B panels advance one tile of bfloat16

    steps = []
    i = starts[0]
    while i < starts[1]:
        line = cmds[i]
        assert "BLOCKWRITE" in line, line
        col = field(line, r"col=(\d+)")
        bdA = field(line, r"bd=(\d+)")
        patch = cmds[i + 1]
        assert "DDR_PATCH" in patch, patch
        arg = field(patch, r"arg_idx=(\d+)")
        off = field(patch, r"arg_off=(\d+)")
        role = "C" if arg == 2 else ("A" if arg == 0 else "B")
        unit = {"C": unitC, "A": unitA, "B": unitB}[role]
        assert off % unit == 0, (name, role, off, unit)
        j = i + 2
        token = "ISSUE_TOKEN" in cmds[j]
        if token:
            j += 1
        push = cmds[j]
        assert "QUEUE_PUSH" in push, push
        chan = field(push, r"ch=(\d+)")
        mm2s = "MM2S" in push
        steps.append(dict(col=col, role=role, slot=off // unit, bdA=bdA,
                          chan=chan, mm2s=mm2s, token=token))
        i = j + 1

    # Second chunk uses a disjoint BD set; chunks 2+ go back to set A.
    bdB = []
    i = starts[1]
    while i < starts[2] and len(bdB) < len(steps):
        if "BLOCKWRITE" in cmds[i]:
            bdB.append(field(cmds[i], r"bd=(\d+)"))
        i += 1
    assert len(bdB) == len(steps), (name, len(bdB), len(steps))
    for s, b in zip(steps, bdB):
        s["bdB"] = b

    waits = [(field(l, r"col=(\d+)"), field(l, r"ch=(\d+)"), "MM2S" in l, field(l, r"w3=0x([0-9a-f]+)", lambda s: int(s, 16)))
             for l in cmds if "WAIT_TCT" in l]
    return steps, waits


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", required=True, help="directory of npu2_<cols>col.insts.bin goldens")
    args = ap.parse_args()
    global golden_dir
    golden_dir = Path(args.dir)

    out = []
    out.append("// Generated by kernels/extract_layout.py -- do not edit by hand.")
    out.append("//")
    out.append("// IRON's placer decides which shim column each buffer descriptor lands on")
    out.append("// and in what order. That decision depends only on the column count, not on")
    out.append("// M/K/N, so it is captured here once per column count and every numeric field")
    out.append("// is computed from the shape at run time. See kernels/INSTS_FORMAT.md.")
    out.append("")
    out.append("#ifndef NEURALNET_RYZENAI_SEQUENCE_LAYOUT_H_")
    out.append("#define NEURALNET_RYZENAI_SEQUENCE_LAYOUT_H_")
    out.append("")
    out.append("#include <cstdint>")
    out.append("")
    out.append("namespace RyzenAISequence {")
    out.append("")
    out.append("enum class Role : uint8_t { C = 0, A = 1, B = 2 };")
    out.append("")
    out.append("struct Step {")
    out.append("  uint8_t col;    // physical shim column")
    out.append("  Role role;      // which kernel argument this descriptor feeds")
    out.append("  uint8_t slot;   // index into that role's DDR partition")
    out.append("  uint8_t bdA;    // buffer descriptor id on even-numbered chunk sets")
    out.append("  uint8_t bdB;    // ... and on chunk 1, which double-buffers against set A")
    out.append("  uint8_t chan;   // DMA channel the queue push targets")
    out.append("  bool mm2s;      // true = host->array, false = array->host")
    out.append("  bool token;     // emit an ISSUE_TOKEN before the queue push")
    out.append("};")
    out.append("")

    names = []
    for cols in COLUMN_COUNTS:
        name = "%dCOL" % cols
        path = golden_dir / ("npu2_%dcol.insts.bin" % cols)
        if not path.exists():
            raise SystemExit("missing golden %s" % path)
        steps, waits = extract(
            name, cols, path, GOLDEN_M, GOLDEN_K, TILE_N * 2 * cols, TILE_M, TILE_K, TILE_N)
        # The WAIT_TCT list is exactly the C descriptors' (col, channel) repeated
        # once per chunk, so it needs no table of its own -- assert that here
        # rather than emitting redundant data.
        cwait = [(s["col"], s["chan"], False) for s in steps if s["role"] == "C"]
        for c in range(len(waits) // len(cwait)):
            got = [(w[0], w[1], w[2]) for w in waits[c * len(cwait):(c + 1) * len(cwait)]]
            assert got == cwait, (name, c, got, cwait)
        names.append((name, cols, len(steps)))
        out.append("// %d column(s): %d descriptors per chunk" % (cols, len(steps)))
        out.append("static const Step LAYOUT_%s[] = {" % name)
        for s in steps:
            out.append("  {%d, Role::%s, %2d, %2d, %2d, %d, %-5s, %-5s},"
                       % (s["col"], s["role"], s["slot"], s["bdA"], s["bdB"], s["chan"],
                          "true" if s["mm2s"] else "false",
                          "true" if s["token"] else "false"))
        out.append("};")
        out.append("")

    out.append("struct Layout { int cols; const Step* steps; int numSteps; };")
    out.append("")
    out.append("static const Layout LAYOUTS[] = {")
    for name, cols, n in names:
        out.append("  {%d, LAYOUT_%s, %d}," % (cols, name, n))
    out.append("};")
    out.append("static const int NUM_LAYOUTS = %d;" % len(names))
    out.append("")
    out.append("}  // namespace RyzenAISequence")
    out.append("")
    out.append("#endif  // NEURALNET_RYZENAI_SEQUENCE_LAYOUT_H_")
    print("\n".join(out))


if __name__ == "__main__":
    main()
