// Generated by python/ryzenai_kernels/extract_layout.py -- do not edit by hand.
//
// IRON's placer decides which shim column each buffer descriptor lands on
// and in what order. That decision depends only on the column count, not on
// M/K/N, so it is captured here once per column count and every numeric field
// is computed from the shape at run time. See python/ryzenai_kernels/INSTS_FORMAT.md.

#ifndef NEURALNET_RYZENAI_SEQUENCE_LAYOUT_H_
#define NEURALNET_RYZENAI_SEQUENCE_LAYOUT_H_

#include <cstdint>

namespace RyzenAISequence {

enum class Role : uint8_t { C = 0, A = 1, B = 2 };

struct Step {
  uint8_t col;    // physical shim column
  Role role;      // which kernel argument this descriptor feeds
  uint8_t slot;   // index into that role's DDR partition
  uint8_t bdA;    // buffer descriptor id on even-numbered chunk sets
  uint8_t bdB;    // ... and on chunk 1, which double-buffers against set A
  uint8_t chan;   // DMA channel the queue push targets
  bool mm2s;      // true = host->array, false = array->host
  bool token;     // emit an ISSUE_TOKEN before the queue push
};

// 1 column(s): 5 descriptors per chunk
static const Step LAYOUT_1COL[] = {
  {0, Role::C,  0,  0,  5, 0, false, true },
  {0, Role::A,  0,  1,  6, 0, true , false},
  {0, Role::B,  0,  2,  7, 1, true , false},
  {0, Role::A,  1,  3,  8, 0, true , false},
  {0, Role::B,  0,  4,  9, 1, true , false},
};

// 2 column(s): 10 descriptors per chunk
static const Step LAYOUT_2COL[] = {
  {0, Role::C,  0,  0,  6, 0, false, true },
  {0, Role::A,  0,  1,  7, 0, true , false},
  {0, Role::B,  0,  2,  8, 1, true , false},
  {0, Role::A,  2,  3,  9, 0, true , false},
  {0, Role::B,  0,  4, 10, 1, true , false},
  {0, Role::C,  1,  5, 11, 1, false, true },
  {1, Role::A,  1,  0,  4, 0, true , false},
  {1, Role::B,  1,  1,  5, 1, true , false},
  {1, Role::A,  3,  2,  6, 0, true , false},
  {1, Role::B,  1,  3,  7, 1, true , false},
};

// 4 column(s): 20 descriptors per chunk
static const Step LAYOUT_4COL[] = {
  {1, Role::C,  0,  0,  6, 0, false, true },
  {0, Role::A,  0,  0,  5, 0, true , false},
  {1, Role::B,  0,  1,  7, 1, true , false},
  {0, Role::A,  4,  1,  6, 0, true , false},
  {1, Role::B,  0,  2,  8, 1, true , false},
  {1, Role::C,  1,  3,  9, 1, false, true },
  {1, Role::A,  1,  4, 10, 0, true , false},
  {0, Role::B,  1,  2,  7, 1, true , false},
  {1, Role::A,  5,  5, 11, 0, true , false},
  {0, Role::B,  1,  3,  8, 1, true , false},
  {0, Role::C,  2,  4,  9, 0, false, true },
  {2, Role::A,  2,  0,  5, 0, true , false},
  {2, Role::B,  2,  1,  6, 1, true , false},
  {2, Role::A,  6,  2,  7, 0, true , false},
  {2, Role::B,  2,  3,  8, 1, true , false},
  {2, Role::C,  3,  4,  9, 0, false, true },
  {3, Role::A,  3,  0,  4, 0, true , false},
  {3, Role::B,  3,  1,  5, 1, true , false},
  {3, Role::A,  7,  2,  6, 0, true , false},
  {3, Role::B,  3,  3,  7, 1, true , false},
};

// 8 column(s): 32 descriptors per chunk
static const Step LAYOUT_8COL[] = {
  {3, Role::C,  0,  0,  6, 0, false, true },
  {0, Role::A,  0,  0,  2, 0, true , false},
  {3, Role::B,  0,  1,  7, 0, true , false},
  {0, Role::A,  8,  1,  3, 0, true , false},
  {3, Role::B,  0,  2,  8, 0, true , false},
  {3, Role::C,  1,  3,  9, 1, false, true },
  {2, Role::A,  2,  0,  5, 0, true , false},
  {3, Role::B,  1,  4, 10, 1, true , false},
  {2, Role::A, 10,  1,  6, 0, true , false},
  {3, Role::B,  1,  5, 11, 1, true , false},
  {2, Role::C,  2,  2,  7, 0, false, true },
  {4, Role::A,  4,  0,  6, 0, true , false},
  {2, Role::B,  2,  3,  8, 1, true , false},
  {4, Role::A, 12,  1,  7, 0, true , false},
  {2, Role::B,  2,  4,  9, 1, true , false},
  {4, Role::C,  3,  2,  8, 0, false, true },
  {6, Role::A,  6,  0,  5, 0, true , false},
  {4, Role::B,  3,  3,  9, 1, true , false},
  {6, Role::A, 14,  1,  6, 0, true , false},
  {4, Role::B,  3,  4, 10, 1, true , false},
  {4, Role::C,  4,  5, 11, 1, false, true },
  {5, Role::B,  4,  0,  6, 0, true , false},
  {5, Role::B,  4,  1,  7, 0, true , false},
  {5, Role::C,  5,  2,  8, 0, false, true },
  {5, Role::B,  5,  3,  9, 1, true , false},
  {5, Role::B,  5,  4, 10, 1, true , false},
  {5, Role::C,  6,  5, 11, 1, false, true },
  {6, Role::B,  6,  2,  7, 1, true , false},
  {6, Role::B,  6,  3,  8, 1, true , false},
  {6, Role::C,  7,  4,  9, 0, false, true },
  {1, Role::B,  7,  0,  2, 0, true , false},
  {1, Role::B,  7,  1,  3, 0, true , false},
};

struct Layout { int cols; const Step* steps; int numSteps; };

static const Layout LAYOUTS[] = {
  {1, LAYOUT_1COL, 5},
  {2, LAYOUT_2COL, 10},
  {4, LAYOUT_4COL, 20},
  {8, LAYOUT_8COL, 32},
};
static const int NUM_LAYOUTS = 4;

}  // namespace RyzenAISequence

#endif  // NEURALNET_RYZENAI_SEQUENCE_LAYOUT_H_
