// sequence.cpp -- see sequence.h for the module overview.
//
// A stream is a run of independent M-chunks of chunkRows = tileM * 4 * 2 rows
// (4 AIE rows, doubled for ping-pong). Within a chunk each buffer descriptor is
// emitted as
//
//   BLOCKWRITE + DDR_PATCH [+ ISSUE_TOKEN] + QUEUE_PUSH
//
// and after the chunks come the WAIT_TCTs. Two things vary between chunks and
// nothing else: the DDR offsets, and which of two buffer-descriptor sets is
// used (chunk 1 double-buffers against chunk 0; chunk 2 onward reuse set A,
// having waited).
//
// The one thing not derivable from (M, K, N, tiles, cols) is which physical
// shim column each descriptor lands on and in what order -- that is IRON's
// placer output. It depends only on the column count, so it is tabulated in
// sequence_layout.h (generated by python/ryzenai_kernels/extract_layout.py) and everything
// numeric is computed here.
//
// Field formulas, with cr = chunkRows and nA = number of A descriptors:
//   C: len = cr*N/2/cols, D0=(tileN,1), D1=(cr/2,N), D2.stride=tileN*cols,
//      iter=(2, cr*N/2), bufoff = chunk*cr*N*4 + slot*tileN*4
//   A: len = cr*K/2/nA,  D0=(tileM,1), D1=(cr/nA,K/2), D2.stride=tileM,
//      iter=(1,1),       bufoff = chunk*cr*K*2 + slot*cr*K/cols
//   B: len = K*tileN/2,  D0=(tileN/2,1), D1=(tileK,N/2), D2.stride=tileK*N/2,
//      iter=(N/tileN/cols, tileN/2*cols), bufoff = slot*tileN*2 (no chunk term:
//      the same B panel feeds every chunk)
//   QUEUE_PUSH.repeat = N/(tileN*cols) - 1 on MM2S; S2MM uses 1 with a token
//
// Two bugs were found here by widening the golden set, both of the same shape:
// a formula that aliased with the right answer at the single point where it had
// been checked. B's D1.stride was written K/2 and only a non-square golden
// showed it must be N/2; C's and A's fields were written as functions of M and
// only a golden with M != 2*chunkRows showed they are chunk constants. Any new
// field formula must be checked against goldens that vary that dimension.

#include "../neuralnet/ryzenaisequence.h"

#include "../neuralnet/ryzenaisequence_layout.h"

#include <stdexcept>
#include <string>

namespace RyzenAISequence {

namespace {

// Command opcodes (see INSTS_FORMAT.md / FastFlowLM op_headers).
constexpr uint32_t OP_WRITE32 = 0x00;
constexpr uint32_t OP_BLOCKWRITE = 0x01;
constexpr uint32_t OP_MASKWRITE = 0x03;
constexpr uint32_t OP_WAIT_TCT = 0x80;
constexpr uint32_t OP_DDR_PATCH = 0x81;

// Register addresses within a shim tile. The full location word additionally
// carries the column in bits 31:25 and the row (always 0 here) in bits 24:20.
constexpr uint32_t ADDR_BD_BASE = 0x1D000;   // descriptor i at +0x20*i
constexpr uint32_t ADDR_BD_PATCH = 0x1D004;  // its address word, for patching
constexpr uint32_t ADDR_QUEUE_S2MM_CH0 = 0x1D204;
constexpr uint32_t ADDR_TOKEN_S2MM_CH0 = 0x1D200;

constexpr uint32_t BD_OPSIZE_BYTES = 12 * 4;
constexpr uint32_t QUEUE_OPSIZE_BYTES = 6 * 4;
constexpr uint32_t TOKEN_OPSIZE_BYTES = 7 * 4;
constexpr uint32_t WAIT_OPSIZE_BYTES = 4 * 4;

// Every design in the artifact set uses the 4 compute rows of a column, and
// each row's tile is double-buffered, so one pass over the array consumes
// tileM*4*2 rows of A. IRON rejects any M that is not a whole number of these.
constexpr uint32_t AIE_ROWS = 4;

void check(bool ok, const char* what) {
  if(!ok)
    throw std::invalid_argument(std::string("RyzenAISequence: invalid shape: ") + what);
}

uint32_t loc(uint32_t col, uint32_t addr) {
  return (col << 25) | addr;  // row is 0: these are all shim-tile registers
}

void pushBlockWrite(
  std::vector<uint32_t>& out,
  uint32_t burstConst,
  uint32_t col,
  uint32_t bdId,
  uint32_t lenBlocks,
  uint32_t bufOffBytes,
  uint32_t d0Size,
  uint32_t d0Stride,
  uint32_t d1Size,
  uint32_t d1Stride,
  uint32_t d2Stride,
  uint32_t iterSize,
  uint32_t iterStride) {
  out.push_back(OP_BLOCKWRITE);
  out.push_back(0);
  out.push_back(loc(col, ADDR_BD_BASE + 0x20 * bdId));
  out.push_back(BD_OPSIZE_BYTES);
  out.push_back(lenBlocks);
  out.push_back(bufOffBytes);
  out.push_back(0);  // packet disabled
  out.push_back((d0Size << 20) | (d0Stride - 1));
  out.push_back(burstConst | (d1Size << 20) | (d1Stride - 1));
  out.push_back((2u << 24) | (d2Stride - 1));  // AxCache=2; D2's size is implied by len
  out.push_back(((iterSize - 1) << 20) | (iterStride - 1));
  // valid_bd=1, lock rel_val=128; everything else zero (as in golden streams).
  out.push_back((1u << 25) | (128u << 18));
}

void pushDdrPatch(
  std::vector<uint32_t>& out, uint32_t col, uint32_t bdId, uint32_t argIdx, uint32_t argOffBytes) {
  out.push_back(OP_DDR_PATCH);
  out.push_back(BD_OPSIZE_BYTES);
  out.push_back(0);
  out.push_back(0);
  out.push_back(0);
  out.push_back(0);
  out.push_back(loc(col, ADDR_BD_PATCH + 0x20 * bdId));
  out.push_back(0);
  out.push_back(argIdx);
  out.push_back(0);
  out.push_back(argOffBytes);
  out.push_back(0);
}

void pushIssueToken(std::vector<uint32_t>& out, uint32_t col, uint32_t channel) {
  // MASKWRITE on the S2MM queue: controller packet id 15.
  out.push_back(OP_MASKWRITE);
  out.push_back(0);
  out.push_back(loc(col, ADDR_TOKEN_S2MM_CH0 + (channel ? 0x8 : 0)));
  out.push_back(0);
  out.push_back(15u << 8);
  out.push_back(0x00001F00u);
  out.push_back(TOKEN_OPSIZE_BYTES);
}

void pushQueuePush(
  std::vector<uint32_t>& out,
  uint32_t col,
  bool mm2s,
  uint32_t channel,
  uint32_t bdId,
  uint32_t repeat,
  bool issueToken) {
  const uint32_t addr = ADDR_QUEUE_S2MM_CH0 + (mm2s ? 0x10 : 0) + (channel ? 0x8 : 0);
  const uint32_t value = (bdId & 0xF) | ((repeat & 0xFF) << 16) | (issueToken ? (1u << 31) : 0);
  out.push_back(OP_WRITE32);
  out.push_back(0);
  out.push_back(loc(col, addr));
  out.push_back(0);
  out.push_back(value);
  out.push_back(QUEUE_OPSIZE_BYTES);
}

void pushWaitTct(std::vector<uint32_t>& out, uint32_t col, uint32_t channel) {
  out.push_back(OP_WAIT_TCT);
  out.push_back(WAIT_OPSIZE_BYTES);
  out.push_back(col << 16);  // row 0, S2MM
  out.push_back((channel << 24) | 0x00010100u);
}

const Layout* findLayout(int cols) {
  for(int i = 0; i < NUM_LAYOUTS; i++) {
    if(LAYOUTS[i].cols == cols)
      return &LAYOUTS[i];
  }
  return nullptr;
}

}  // namespace

bool supportsColumns(int cols) {
  return findLayout(cols) != nullptr;
}

std::vector<uint32_t> generateSequence(
  Arch arch, int cols, int M, int K, int N, int tileM, int tileK, int tileN) {
  GemmShape shape{M, K, N, tileM, tileK, tileN};
  return generateSequence(arch, cols, shape);
}

std::vector<uint32_t> generateSingleColSequence(Arch arch, const GemmShape& shape) {
  return generateSequence(arch, 1, shape);
}

std::vector<uint32_t> generateSingleColSequence(
  Arch arch, int M, int K, int N, int tileM, int tileK, int tileN) {
  return generateSequence(arch, 1, M, K, N, tileM, tileK, tileN);
}

std::vector<uint32_t> generateSequence(Arch arch, int cols, const GemmShape& s) {
  const Layout* layout = findLayout(cols);
  if(layout == nullptr)
    throw std::invalid_argument(
      "RyzenAISequence: no descriptor layout for " + std::to_string(cols) + " column(s)");

  check(s.M > 0 && s.K > 0 && s.N > 0, "M/K/N must be positive");
  check(s.tileM > 0 && s.tileK > 0 && s.tileN > 0, "tiles must be positive");
  check(s.K % s.tileK == 0, "K % tileK != 0");
  check(s.tileN % 2 == 0, "tileN must be even");
  check(s.N % (s.tileN * cols) == 0, "N % (tileN*cols) != 0");
  check((s.N / (s.tileN * cols) - 1) <= 0xFF, "N/(tileN*cols)-1 overflows QUEUE_PUSH.repeat");

  const uint32_t M = static_cast<uint32_t>(s.M);
  const uint32_t K = static_cast<uint32_t>(s.K);
  const uint32_t N = static_cast<uint32_t>(s.N);
  const uint32_t tm = static_cast<uint32_t>(s.tileM);
  const uint32_t tk = static_cast<uint32_t>(s.tileK);
  const uint32_t tn = static_cast<uint32_t>(s.tileN);
  const uint32_t nCols = static_cast<uint32_t>(cols);

  const uint32_t chunkRows = tm * AIE_ROWS * 2;
  check(s.M % (int)chunkRows == 0,
        "M must be a multiple of tileM*8 (one pass over the 4 double-buffered AIE rows)");
  const uint32_t chunks = M / chunkRows;

  uint32_t numA = 0;
  for(int i = 0; i < layout->numSteps; i++)
    numA += (layout->steps[i].role == Role::A) ? 1u : 0u;

  // Per-descriptor transfer sizes, in the 4-word blocks the length field counts.
  const uint32_t lenC = chunkRows * N / 2 / nCols;
  const uint32_t lenA = chunkRows * K / 2 / numA;
  const uint32_t lenB = K * tn / 2;
  // Units the DDR offsets step by, matching the slot indices in the layout.
  const uint32_t unitC = tn * 4;        // one tile of float32 output
  const uint32_t unitA = chunkRows * K / nCols;
  const uint32_t unitB = tn * 2;        // one tile of bfloat16
  const uint32_t stripsPerCol = N / (tn * nCols);
  const uint32_t repeatMm2s = stripsPerCol - 1;

  // Normally a C descriptor covers one output tile and is re-issued once per
  // half-chunk (queue repeat 1, iter walking the two halves). When a column
  // owns exactly one tile there is no strip loop left to run, so IRON folds the
  // two halves into the descriptor instead: double the length, walk the halves
  // with D2, and issue it once. Both encodings move the same bytes.
  const bool foldC = stripsPerCol < 2;
  const uint32_t lenCEff = foldC ? (chunkRows * N / nCols) : lenC;
  const uint32_t d2C = foldC ? (chunkRows * N / 2) : (tn * nCols);
  const uint32_t iterSizeC = foldC ? 1u : 2u;
  const uint32_t iterStrideC = foldC ? 1u : (chunkRows * N / 2);
  const uint32_t repeatS2mm = foldC ? 0u : 1u;
  // A one-iteration loop carries no stride.
  const uint32_t iterStrideB = (stripsPerCol == 1) ? 1u : (tn / 2 * nCols);

  std::vector<uint32_t> out;
  out.reserve(4 + chunks * (layout->numSteps * 31 + nCols * 4));

  // Header: n_rows=6, gen from arch, minor=1, major=0; mem_tile_rows=1.
  // The num_cols byte is the device's physical width, not the design's: npu2
  // streams carry 8 even for a 1-column design. npu1 1-column streams carry 1.
  const uint32_t gen = static_cast<uint32_t>(arch);
  const uint32_t physCols = (arch == Arch::NPU1 && cols == 1) ? 1u : (arch == Arch::NPU1 ? 4u : 8u);
  out.push_back((6u << 24) | (gen << 16) | (1u << 8));
  out.push_back((1u << 8) | physCols);
  out.push_back(0);  // command count, patched at the end
  out.push_back(0);  // total bytes, patched at the end

  // BLOCKWRITE D1 word burst-size constant differs between generations:
  // 0xC0000000 on npu2 (aie2p), 0x80000000 on npu1 (aie2).
  const uint32_t burstConst = (arch == Arch::NPU1) ? 0x80000000u : 0xC0000000u;

  uint32_t numCommands = 0;
  for(uint32_t chunk = 0; chunk < chunks; ++chunk) {
    // Chunk 1 is the only one that needs its own descriptor set: it is issued
    // before chunk 0's tokens are collected. From chunk 2 on there is always an
    // intervening wait, so set A is free again.
    const bool setB = (chunk == 1);

    for(int i = 0; i < layout->numSteps; i++) {
      const Step& step = layout->steps[i];
      const uint32_t col = step.col;
      const uint32_t bd = setB ? step.bdB : step.bdA;
      const uint32_t slot = step.slot;

      uint32_t argIdx, off;
      switch(step.role) {
        case Role::C:
          off = chunk * chunkRows * N * 4 + slot * unitC;
          argIdx = 2;
          pushBlockWrite(
            out, burstConst, col, bd, lenCEff, off, tn, 1, chunkRows / 2, N, d2C, iterSizeC,
            iterStrideC);
          break;
        case Role::A:
          off = chunk * chunkRows * K * 2 + slot * unitA;
          argIdx = 0;
          pushBlockWrite(
            out, burstConst, col, bd, lenA, off, tm, 1, chunkRows / numA, K / 2, tm, 1, 1);
          break;
        default:  // Role::B -- the same panel is re-read by every chunk
          off = slot * unitB;
          argIdx = 1;
          pushBlockWrite(
            out, burstConst, col, bd, lenB, off, tn / 2, 1, tk, N / 2, tk * N / 2, stripsPerCol,
            iterStrideB);
          break;
      }
      pushDdrPatch(out, col, bd, argIdx, off);
      numCommands += 2;

      if(step.token) {
        pushIssueToken(out, col, step.chan);
        numCommands++;
      }
      pushQueuePush(
        out, col, step.mm2s, step.chan, bd, step.mm2s ? repeatMm2s : repeatS2mm, step.token);
      numCommands++;
    }

    // One token per C descriptor per chunk. Chunk 0's are collected together
    // with chunk 1's, which is what lets those two chunks overlap.
    const uint32_t pending = (chunk == 0 && chunks > 1) ? 0 : (chunk == 1 ? 2 : 1);
    for(uint32_t rep = 0; rep < pending; rep++) {
      for(int i = 0; i < layout->numSteps; i++) {
        if(layout->steps[i].role != Role::C)
          continue;
        pushWaitTct(out, layout->steps[i].col, layout->steps[i].chan);
        numCommands++;
      }
    }
  }

  out[2] = numCommands;
  out[3] = static_cast<uint32_t>(out.size() * 4);
  return out;
}

}  // namespace RyzenAISequence
