#!/usr/bin/python3
from typing import Dict, Any

ModelConfig = Dict[str,Any]

# version = 0 #V1 features, with old head architecture using crelus (no longer supported)
# version = 1 #V1 features, with new head architecture, no crelus
# version = 2 #V2 features, no internal architecture change.
# version = 3 #V3 features, selfplay-planned features with lots of aux targets
# version = 4 #V3 features, but supporting belief stdev and dynamic scorevalue
# version = 5 #V4 features, slightly different pass-alive stones feature
# version = 6 #V5 features, most higher-level go features removed
# version = 7 #V6 features, more rules support
# version = 8 #V7 features, asym, lead, variance time
# version = 9 #V7 features, shortterm value error prediction, inference actually uses variance time, unsupported now
# version = 10 #V7 features, shortterm value error prediction done properly

def get_version(config: ModelConfig):
  return config["version"]

def get_num_bin_input_features(config: ModelConfig):
  version = get_version(config)
  if version == 10:
    return 22
  else:
    assert(False)

def get_num_global_input_features(config: ModelConfig):
  version = get_version(config)
  if version == 10:
    return 19
  else:
    assert(False)

b2c16 = {
  "version":10,
  "norm_kind":"fixup",
  "bnorm_epsilon": 1e-4,
  "bnorm_running_avg_momentum": 0.001,
  "trunk_num_channels":16,
  "mid_num_channels":16,
  "regular_num_channels":8,
  "dilated_num_channels":8,
  "gpool_num_channels":8,
  "use_attention_pool":False,
  "num_attention_pool_heads":2,
  "block_kind": [
    ["rconv1","regular"],
    ["rconv2","gpool"],
  ],
  "p1_num_channels":8,
  "g1_num_channels":8,
  "v1_num_channels":8,
  "sbv2_num_channels":12,
  "num_scorebeliefs":2,
  "v2_size":12,
}

b4c32 = {
  "version":10,
  "norm_kind":"fixup",
  "bnorm_epsilon": 1e-4,
  "bnorm_running_avg_momentum": 0.001,
  "trunk_num_channels":32,
  "mid_num_channels":32,
  "regular_num_channels":16,
  "dilated_num_channels":16,
  "gpool_num_channels":16,
  "use_attention_pool":False,
  "num_attention_pool_heads":4,
  "block_kind": [
    ["rconv1","regular"],
    ["rconv2","regular"],
    ["rconv3","gpool"],
    ["rconv4","regular"],
  ],
  "p1_num_channels":12,
  "g1_num_channels":12,
  "v1_num_channels":12,
  "sbv2_num_channels":24,
  "num_scorebeliefs":4,
  "v2_size":24,
}

b6c96 = {
  "version":10,
  "norm_kind":"fixup",
  "bnorm_epsilon": 1e-4,
  "bnorm_running_avg_momentum": 0.001,
  "trunk_num_channels":96,
  "mid_num_channels":96,
  "regular_num_channels":64,
  "dilated_num_channels":32,
  "gpool_num_channels":32,
  "use_attention_pool":False,
  "num_attention_pool_heads":8,
  "block_kind": [
    ["rconv1","regular"],
    ["rconv2","regular"],
    ["rconv3","gpool"],
    ["rconv4","regular"],
    ["rconv5","gpool"],
    ["rconv6","regular"],
  ],
  "p1_num_channels":32,
  "g1_num_channels":32,
  "v1_num_channels":32,
  "sbv2_num_channels":48,
  "num_scorebeliefs":4,
  "v2_size":64,
}

b10c128 = {
  "version":10,
  "norm_kind":"fixup",
  "bnorm_epsilon": 1e-4,
  "bnorm_running_avg_momentum": 0.001,
  "trunk_num_channels":128,
  "mid_num_channels":128,
  "regular_num_channels":96,
  "dilated_num_channels":32,
  "gpool_num_channels":32,
  "use_attention_pool":False,
  "num_attention_pool_heads":8,
  "block_kind": [
    ["rconv1","regular"],
    ["rconv2","regular"],
    ["rconv3","regular"],
    ["rconv4","regular"],
    ["rconv5","gpool"],
    ["rconv6","regular"],
    ["rconv7","regular"],
    ["rconv8","gpool"],
    ["rconv9","regular"],
    ["rconv10","regular"],
  ],
  "p1_num_channels":32,
  "g1_num_channels":32,
  "v1_num_channels":32,
  "sbv2_num_channels":64,
  "num_scorebeliefs":6,
  "v2_size":80,
}

b15c192 = {
  "version":10,
  "norm_kind":"fixup",
  "bnorm_epsilon": 1e-4,
  "bnorm_running_avg_momentum": 0.001,
  "trunk_num_channels":192,
  "mid_num_channels":192,
  "regular_num_channels":128,
  "dilated_num_channels":64,
  "gpool_num_channels":64,
  "use_attention_pool":False,
  "num_attention_pool_heads":8,
  "block_kind": [
    ["rconv1","regular"],
    ["rconv2","regular"],
    ["rconv3","regular"],
    ["rconv4","regular"],
    ["rconv5","regular"],
    ["rconv6","regular"],
    ["rconv7","gpool"],
    ["rconv8","regular"],
    ["rconv9","regular"],
    ["rconv10","regular"],
    ["rconv11","regular"],
    ["rconv12","gpool"],
    ["rconv13","regular"],
    ["rconv14","regular"],
    ["rconv15","regular"],
  ],
  "p1_num_channels":32,
  "g1_num_channels":32,
  "v1_num_channels":32,
  "sbv2_num_channels":80,
  "num_scorebeliefs":8,
  "v2_size":96,
}

b11c384llbt = {
  "version":10,
  "norm_kind":"fixup",
  "bnorm_epsilon": 1e-4,
  "bnorm_running_avg_momentum": 0.001,
  "trunk_num_channels":384,
  "mid_num_channels":192,
  "regular_num_channels":128,
  "dilated_num_channels":64,
  "gpool_num_channels":64,
  "use_attention_pool":False,
  "num_attention_pool_heads":8,
  "block_kind": [
    ["rconv1","longlongbottle"],
    ["rconv2","longlongbottle"],
    ["rconv4","longlongbottlegpool"],
    ["rconv5","longlongbottle"],
    ["rconv6","longlongbottle"],
    ["rconv7","longlongbottlegpool"],
    ["rconv8","longlongbottle"],
    ["rconv9","longlongbottle"],
    ["rconv10","longlongbottlegpool"],
    ["rconv11","longlongbottle"],
    ["rconv12","longlongbottle"],
  ],
  "p1_num_channels":48,
  "g1_num_channels":48,
  "v1_num_channels":48,
  "sbv2_num_channels":96,
  "num_scorebeliefs":8,
  "v2_size":112,
}

b20c256 = {
  "version":10,
  "norm_kind":"fixup",
  "bnorm_epsilon": 1e-4,
  "bnorm_running_avg_momentum": 0.001,
  "trunk_num_channels":256,
  "mid_num_channels":256,
  "regular_num_channels":192,
  "dilated_num_channels":64,
  "gpool_num_channels":64,
  "use_attention_pool":False,
  "num_attention_pool_heads":8,
  "block_kind": [
    ["rconv1","regular"],
    ["rconv2","regular"],
    ["rconv3","regular"],
    ["rconv4","regular"],
    ["rconv5","regular"],
    ["rconv6","regular"],
    ["rconv7","gpool"],
    ["rconv8","regular"],
    ["rconv9","regular"],
    ["rconv10","regular"],
    ["rconv11","regular"],
    ["rconv12","gpool"],
    ["rconv13","regular"],
    ["rconv14","regular"],
    ["rconv15","regular"],
    ["rconv16","regular"],
    ["rconv17","gpool"],
    ["rconv18","regular"],
    ["rconv19","regular"],
    ["rconv20","regular"],
  ],
  "p1_num_channels":48,
  "g1_num_channels":48,
  "v1_num_channels":48,
  "sbv2_num_channels":96,
  "num_scorebeliefs":8,
  "v2_size":112,
}

b30c256bt = {
  "version":10,
  "norm_kind":"fixup",
  "bnorm_epsilon": 1e-4,
  "bnorm_running_avg_momentum": 0.001,
  "trunk_num_channels":256,
  "mid_num_channels":128,
  "regular_num_channels":64,
  "dilated_num_channels":64,
  "gpool_num_channels":64,
  "use_attention_pool":False,
  "num_attention_pool_heads":8,
  "block_kind": [
    ["rconv0","bottle"],
    ["rconv1","bottle"],
    ["rconv2","bottle"],
    ["rconv3","bottle"],
    ["rconv4","bottle"],
    ["rconv5","bottle"],
    ["rconv6","bottlegpool"],
    ["rconv7","bottle"],
    ["rconv8","bottle"],
    ["rconv9","bottle"],
    ["rconv10","bottle"],
    ["rconv11","bottle"],
    ["rconv12","bottlegpool"],
    ["rconv13","bottle"],
    ["rconv14","bottle"],
    ["rconv15","bottle"],
    ["rconv16","bottle"],
    ["rconv17","bottle"],
    ["rconv18","bottlegpool"],
    ["rconv19","bottle"],
    ["rconv20","bottle"],
    ["rconv21","bottle"],
    ["rconv22","bottle"],
    ["rconv23","bottle"],
    ["rconv24","bottlegpool"],
    ["rconv25","bottle"],
    ["rconv26","bottle"],
    ["rconv27","bottle"],
    ["rconv28","bottle"],
    ["rconv29","bottle"],
  ],
  "p1_num_channels":48,
  "g1_num_channels":48,
  "v1_num_channels":48,
  "sbv2_num_channels":96,
  "num_scorebeliefs":8,
  "v2_size":112,
}

b24c320bt = {
  "version":10,
  "norm_kind":"fixup",
  "bnorm_epsilon": 1e-4,
  "bnorm_running_avg_momentum": 0.001,
  "trunk_num_channels":320,
  "mid_num_channels":160,
  "regular_num_channels":96,
  "dilated_num_channels":64,
  "gpool_num_channels":64,
  "use_attention_pool":False,
  "num_attention_pool_heads":8,
  "block_kind": [
    ["rconv1","bottle"],
    ["rconv2","bottle"],
    ["rconv3","bottle"],
    ["rconv4","bottle"],
    ["rconv5","bottle"],
    ["rconv6","bottle"],
    ["rconv7","bottlegpool"],
    ["rconv8","bottle"],
    ["rconv9","bottle"],
    ["rconv10","bottle"],
    ["rconv11","bottle"],
    ["rconv12","bottle"],
    ["rconv13","bottlegpool"],
    ["rconv14","bottle"],
    ["rconv15","bottle"],
    ["rconv16","bottle"],
    ["rconv17","bottle"],
    ["rconv18","bottle"],
    ["rconv19","bottlegpool"],
    ["rconv20","bottle"],
    ["rconv21","bottle"],
    ["rconv22","bottle"],
    ["rconv23","bottle"],
    ["rconv24","bottle"],
  ],
  "p1_num_channels":48,
  "g1_num_channels":48,
  "v1_num_channels":48,
  "sbv2_num_channels":96,
  "num_scorebeliefs":8,
  "v2_size":112,
}

b20c384bt = {
  "version":10,
  "norm_kind":"fixup",
  "bnorm_epsilon": 1e-4,
  "bnorm_running_avg_momentum": 0.001,
  "trunk_num_channels":384,
  "mid_num_channels":192,
  "regular_num_channels":128,
  "dilated_num_channels":64,
  "gpool_num_channels":64,
  "use_attention_pool":False,
  "num_attention_pool_heads":8,
  "block_kind": [
    ["rconv1","bottle"],
    ["rconv2","bottle"],
    ["rconv3","bottle"],
    ["rconv4","bottle"],
    ["rconv5","bottle"],
    ["rconv6","bottlegpool"],
    ["rconv7","bottle"],
    ["rconv8","bottle"],
    ["rconv9","bottle"],
    ["rconv10","bottle"],
    ["rconv11","bottlegpool"],
    ["rconv12","bottle"],
    ["rconv13","bottle"],
    ["rconv14","bottle"],
    ["rconv15","bottle"],
    ["rconv16","bottlegpool"],
    ["rconv17","bottle"],
    ["rconv18","bottle"],
    ["rconv19","bottle"],
    ["rconv20","bottle"],
  ],
  "p1_num_channels":48,
  "g1_num_channels":48,
  "v1_num_channels":48,
  "sbv2_num_channels":96,
  "num_scorebeliefs":8,
  "v2_size":112,
}


b10c512lbt = {
  "version":10,
  "norm_kind":"fixup",
  "bnorm_epsilon": 1e-4,
  "bnorm_running_avg_momentum": 0.001,
  "trunk_num_channels":512,
  "mid_num_channels":256,
  "regular_num_channels":128,
  "dilated_num_channels":128,
  "gpool_num_channels":128,
  "use_attention_pool":False,
  "num_attention_pool_heads":8,
  "block_kind": [
    ["rconv1","longbottle"],
    ["rconv2","longbottle"],
    ["rconv3","longbottle"],
    ["rconv4","longbottlegpool"],
    ["rconv5","longbottle"],
    ["rconv6","longbottle"],
    ["rconv7","longbottle"],
    ["rconv8","longbottlegpool"],
    ["rconv9","longbottle"],
    ["rconv10","longbottle"],
  ],
  "p1_num_channels":48,
  "g1_num_channels":48,
  "v1_num_channels":48,
  "sbv2_num_channels":96,
  "num_scorebeliefs":8,
  "v2_size":112,
}


b15c384lbt = {
  "version":10,
  "norm_kind":"fixup",
  "bnorm_epsilon": 1e-4,
  "bnorm_running_avg_momentum": 0.001,
  "trunk_num_channels":384,
  "mid_num_channels":192,
  "regular_num_channels":128,
  "dilated_num_channels":64,
  "gpool_num_channels":64,
  "use_attention_pool":False,
  "num_attention_pool_heads":8,
  "block_kind": [
    ["rconv1","longbottle"],
    ["rconv2","longbottle"],
    ["rconv3","longbottle"],
    ["rconv4","longbottlegpool"],
    ["rconv5","longbottle"],
    ["rconv6","longbottle"],
    ["rconv7","longbottle"],
    ["rconv8","longbottlegpool"],
    ["rconv9","longbottle"],
    ["rconv10","longbottle"],
    ["rconv11","longbottle"],
    ["rconv12","longbottlegpool"],
    ["rconv13","longbottle"],
    ["rconv14","longbottle"],
    ["rconv15","longbottle"],
  ],
  "p1_num_channels":48,
  "g1_num_channels":48,
  "v1_num_channels":48,
  "sbv2_num_channels":96,
  "num_scorebeliefs":8,
  "v2_size":112,
}

b18c320lbt = {
  "version":10,
  "norm_kind":"fixup",
  "bnorm_epsilon": 1e-4,
  "bnorm_running_avg_momentum": 0.001,
  "trunk_num_channels":320,
  "mid_num_channels":160,
  "regular_num_channels":96,
  "dilated_num_channels":64,
  "gpool_num_channels":64,
  "use_attention_pool":False,
  "num_attention_pool_heads":8,
  "block_kind": [
    ["rconv1","longbottle"],
    ["rconv2","longbottle"],
    ["rconv3","longbottle"],
    ["rconv4","longbottle"],
    ["rconv5","longbottlegpool"],
    ["rconv6","longbottle"],
    ["rconv7","longbottle"],
    ["rconv8","longbottle"],
    ["rconv9","longbottle"],
    ["rconv10","longbottlegpool"],
    ["rconv11","longbottle"],
    ["rconv12","longbottle"],
    ["rconv13","longbottle"],
    ["rconv14","longbottle"],
    ["rconv15","longbottlegpool"],
    ["rconv16","longbottle"],
    ["rconv17","longbottle"],
    ["rconv18","longbottle"],
  ],
  "p1_num_channels":48,
  "g1_num_channels":48,
  "v1_num_channels":48,
  "sbv2_num_channels":96,
  "num_scorebeliefs":8,
  "v2_size":112,
}

b23c256lbt = {
  "version":10,
  "norm_kind":"fixup",
  "bnorm_epsilon": 1e-4,
  "bnorm_running_avg_momentum": 0.001,
  "trunk_num_channels":256,
  "mid_num_channels":128,
  "regular_num_channels":64,
  "dilated_num_channels":64,
  "gpool_num_channels":64,
  "use_attention_pool":False,
  "num_attention_pool_heads":8,
  "block_kind": [
    ["rconv1","longbottle"],
    ["rconv2","longbottle"],
    ["rconv3","longbottle"],
    ["rconv4","longbottle"],
    ["rconv5","longbottle"],
    ["rconv6","longbottlegpool"],
    ["rconv7","longbottle"],
    ["rconv8","longbottle"],
    ["rconv9","longbottle"],
    ["rconv10","longbottle"],
    ["rconv11","longbottle"],
    ["rconv12","longbottlegpool"],
    ["rconv13","longbottle"],
    ["rconv14","longbottle"],
    ["rconv15","longbottle"],
    ["rconv16","longbottle"],
    ["rconv17","longbottle"],
    ["rconv18","longbottlegpool"],
    ["rconv19","longbottle"],
    ["rconv20","longbottle"],
    ["rconv21","longbottle"],
    ["rconv22","longbottle"],
    ["rconv23","longbottle"],
  ],
  "p1_num_channels":48,
  "g1_num_channels":48,
  "v1_num_channels":48,
  "sbv2_num_channels":96,
  "num_scorebeliefs":8,
  "v2_size":112,
}

b12c384llbt = {
  "version":10,
  "norm_kind":"fixup",
  "bnorm_epsilon": 1e-4,
  "bnorm_running_avg_momentum": 0.001,
  "trunk_num_channels":384,
  "mid_num_channels":192,
  "regular_num_channels":128,
  "dilated_num_channels":64,
  "gpool_num_channels":64,
  "use_attention_pool":False,
  "num_attention_pool_heads":8,
  "block_kind": [
    ["rconv1","longlongbottle"],
    ["rconv2","longlongbottle"],
    ["rconv3","longlongbottle"],
    ["rconv4","longlongbottlegpool"],
    ["rconv5","longlongbottle"],
    ["rconv6","longlongbottle"],
    ["rconv7","longlongbottlegpool"],
    ["rconv8","longlongbottle"],
    ["rconv9","longlongbottle"],
    ["rconv10","longlongbottlegpool"],
    ["rconv11","longlongbottle"],
    ["rconv12","longlongbottle"],
  ],
  "p1_num_channels":48,
  "g1_num_channels":48,
  "v1_num_channels":48,
  "sbv2_num_channels":96,
  "num_scorebeliefs":8,
  "v2_size":112,
}


b20c384lbt = {
  "version":10,
  "norm_kind":"fixup",
  "bnorm_epsilon": 1e-4,
  "bnorm_running_avg_momentum": 0.001,
  "trunk_num_channels":384,
  "mid_num_channels":192,
  "regular_num_channels":128,
  "dilated_num_channels":64,
  "gpool_num_channels":64,
  "use_attention_pool":False,
  "num_attention_pool_heads":8,
  "block_kind": [
    ["rconv1","longbottle"],
    ["rconv2","longbottle"],
    ["rconv3","longbottle"],
    ["rconv4","longbottle"],
    ["rconv5","longbottle"],
    ["rconv6","longbottlegpool"],
    ["rconv7","longbottle"],
    ["rconv8","longbottle"],
    ["rconv9","longbottle"],
    ["rconv10","longbottle"],
    ["rconv11","longbottlegpool"],
    ["rconv12","longbottle"],
    ["rconv13","longbottle"],
    ["rconv14","longbottle"],
    ["rconv15","longbottle"],
    ["rconv16","longbottlegpool"],
    ["rconv17","longbottle"],
    ["rconv18","longbottle"],
    ["rconv19","longbottle"],
    ["rconv20","longbottle"],
  ],
  "p1_num_channels":48,
  "g1_num_channels":48,
  "v1_num_channels":48,
  "sbv2_num_channels":96,
  "num_scorebeliefs":8,
  "v2_size":112,
}


b30c320 = {
  "version":10,
  "norm_kind":"fixup",
  "bnorm_epsilon": 1e-4,
  "bnorm_running_avg_momentum": 0.001,
  "trunk_num_channels":320,
  "mid_num_channels":320,
  "regular_num_channels":224,
  "dilated_num_channels":96,
  "gpool_num_channels":96,
  "use_attention_pool":False,
  "num_attention_pool_heads":8,
  "block_kind": [
    ["rconv1","regular"],
    ["rconv2","regular"],
    ["rconv3","regular"],
    ["rconv4","regular"],
    ["rconv5","regular"],
    ["rconv6","gpool"],
    ["rconv7","regular"],
    ["rconv8","regular"],
    ["rconv9","regular"],
    ["rconv10","regular"],
    ["rconv11","gpool"],
    ["rconv12","regular"],
    ["rconv13","regular"],
    ["rconv14","regular"],
    ["rconv15","regular"],
    ["rconv16","gpool"],
    ["rconv17","regular"],
    ["rconv18","regular"],
    ["rconv19","regular"],
    ["rconv20","regular"],
    ["rconv21","gpool"],
    ["rconv22","regular"],
    ["rconv23","regular"],
    ["rconv24","regular"],
    ["rconv25","regular"],
    ["rconv26","gpool"],
    ["rconv27","regular"],
    ["rconv28","regular"],
    ["rconv29","regular"],
    ["rconv30","regular"],
  ],
  "p1_num_channels":48,
  "g1_num_channels":48,
  "v1_num_channels":48,
  "sbv2_num_channels":112,
  "num_scorebeliefs":8,
  "v2_size":128,
}

b40c256 = {
  "version":10,
  "norm_kind":"fixup",
  "bnorm_epsilon": 1e-4,
  "bnorm_running_avg_momentum": 0.001,
  "trunk_num_channels":256,
  "mid_num_channels":256,
  "regular_num_channels":192,
  "dilated_num_channels":64,
  "gpool_num_channels":64,
  "use_attention_pool":False,
  "num_attention_pool_heads":8,
  "block_kind": [
    ["rconv1","regular"],
    ["rconv2","regular"],
    ["rconv3","regular"],
    ["rconv4","regular"],
    ["rconv5","regular"],
    ["rconv6","gpool"],
    ["rconv7","regular"],
    ["rconv8","regular"],
    ["rconv9","regular"],
    ["rconv10","regular"],
    ["rconv11","gpool"],
    ["rconv12","regular"],
    ["rconv13","regular"],
    ["rconv14","regular"],
    ["rconv15","regular"],
    ["rconv16","gpool"],
    ["rconv17","regular"],
    ["rconv18","regular"],
    ["rconv19","regular"],
    ["rconv20","regular"],
    ["rconv21","gpool"],
    ["rconv22","regular"],
    ["rconv23","regular"],
    ["rconv24","regular"],
    ["rconv25","regular"],
    ["rconv26","gpool"],
    ["rconv27","regular"],
    ["rconv28","regular"],
    ["rconv29","regular"],
    ["rconv30","regular"],
    ["rconv31","gpool"],
    ["rconv32","regular"],
    ["rconv33","regular"],
    ["rconv34","regular"],
    ["rconv35","regular"],
    ["rconv36","gpool"],
    ["rconv37","regular"],
    ["rconv38","regular"],
    ["rconv39","regular"],
    ["rconv40","regular"],
  ],
  "p1_num_channels":48,
  "g1_num_channels":48,
  "v1_num_channels":48,
  "sbv2_num_channels":112,
  "num_scorebeliefs":8,
  "v2_size":128,
}

b40c384 = {
  "version":10,
  "norm_kind":"fixup",
  "bnorm_epsilon": 1e-4,
  "bnorm_running_avg_momentum": 0.001,
  "trunk_num_channels":384,
  "mid_num_channels":384,
  "regular_num_channels":256,
  "dilated_num_channels":128,
  "gpool_num_channels":128,
  "use_attention_pool":False,
  "num_attention_pool_heads":8,
  "block_kind": [
    ["rconv1","regular"],
    ["rconv2","regular"],
    ["rconv3","regular"],
    ["rconv4","regular"],
    ["rconv5","regular"],
    ["rconv6","gpool"],
    ["rconv7","regular"],
    ["rconv8","regular"],
    ["rconv9","regular"],
    ["rconv10","regular"],
    ["rconv11","gpool"],
    ["rconv12","regular"],
    ["rconv13","regular"],
    ["rconv14","regular"],
    ["rconv15","regular"],
    ["rconv16","gpool"],
    ["rconv17","regular"],
    ["rconv18","regular"],
    ["rconv19","regular"],
    ["rconv20","regular"],
    ["rconv21","gpool"],
    ["rconv22","regular"],
    ["rconv23","regular"],
    ["rconv24","regular"],
    ["rconv25","regular"],
    ["rconv26","gpool"],
    ["rconv27","regular"],
    ["rconv28","regular"],
    ["rconv29","regular"],
    ["rconv30","regular"],
    ["rconv31","gpool"],
    ["rconv32","regular"],
    ["rconv33","regular"],
    ["rconv34","regular"],
    ["rconv35","regular"],
    ["rconv36","gpool"],
    ["rconv37","regular"],
    ["rconv38","regular"],
    ["rconv39","regular"],
    ["rconv40","regular"],
  ],
  "p1_num_channels":64,
  "g1_num_channels":64,
  "v1_num_channels":64,
  "sbv2_num_channels":128,
  "num_scorebeliefs":8,
  "v2_size":144,
}


b60c320 = {
  "version":10,
  "norm_kind":"fixup",
  "bnorm_epsilon": 1e-4,
  "bnorm_running_avg_momentum": 0.001,
  "trunk_num_channels":320,
  "mid_num_channels":320,
  "regular_num_channels":224,
  "dilated_num_channels":96,
  "gpool_num_channels":96,
  "use_attention_pool":False,
  "num_attention_pool_heads":8,
  "block_kind": [
    ["rconv1","regular"],
    ["rconv2","regular"],
    ["rconv3","regular"],
    ["rconv4","regular"],
    ["rconv5","regular"],
    ["rconv6","gpool"],
    ["rconv7","regular"],
    ["rconv8","regular"],
    ["rconv9","regular"],
    ["rconv10","regular"],
    ["rconv11","gpool"],
    ["rconv12","regular"],
    ["rconv13","regular"],
    ["rconv14","regular"],
    ["rconv15","regular"],
    ["rconv16","gpool"],
    ["rconv17","regular"],
    ["rconv18","regular"],
    ["rconv19","regular"],
    ["rconv20","regular"],
    ["rconv21","gpool"],
    ["rconv22","regular"],
    ["rconv23","regular"],
    ["rconv24","regular"],
    ["rconv25","regular"],
    ["rconv26","gpool"],
    ["rconv27","regular"],
    ["rconv28","regular"],
    ["rconv29","regular"],
    ["rconv30","regular"],
    ["rconv31","gpool"],
    ["rconv32","regular"],
    ["rconv33","regular"],
    ["rconv34","regular"],
    ["rconv35","regular"],
    ["rconv36","gpool"],
    ["rconv37","regular"],
    ["rconv38","regular"],
    ["rconv39","regular"],
    ["rconv40","regular"],
    ["rconv41","gpool"],
    ["rconv42","regular"],
    ["rconv43","regular"],
    ["rconv44","regular"],
    ["rconv45","regular"],
    ["rconv46","gpool"],
    ["rconv47","regular"],
    ["rconv48","regular"],
    ["rconv49","regular"],
    ["rconv50","regular"],
    ["rconv51","gpool"],
    ["rconv52","regular"],
    ["rconv53","regular"],
    ["rconv54","regular"],
    ["rconv55","regular"],
    ["rconv56","gpool"],
    ["rconv57","regular"],
    ["rconv58","regular"],
    ["rconv59","regular"],
    ["rconv60","regular"],
   ],
  "p1_num_channels":64,
  "g1_num_channels":64,
  "v1_num_channels":64,
  "sbv2_num_channels":128,
  "num_scorebeliefs":8,
  "v2_size":144,
}

sandbox = {
  "version":10,
  "norm_kind":"fixup",
  "bnorm_epsilon": 1e-4,
  "bnorm_running_avg_momentum": 0.001,
  "trunk_num_channels":256,
  "mid_num_channels":256,
  "regular_num_channels":192,
  "dilated_num_channels":64,
  "gpool_num_channels":64,
  "use_attention_pool":False,
  "num_attention_pool_heads":8,
  "block_kind": [
    ["rconv1","regular"],
    ["rconv2","regular"],
    ["rconv3","regular"],
    ["rconv4","regular"],
    ["rconv5","regular"],
    ["rconv6","regular"],
    ["rconv7","gpool"],
    ["rconv8","regular"],
    ["rconv9","regular"],
    ["rconv10","regular"],
    ["rconv11","regular"],
    ["rconv12","gpool"],
    ["rconv13","regular"],
    ["rconv14","regular"],
    ["rconv15","regular"],
    ["rconv16","regular"],
    ["rconv17","gpool"],
    ["rconv18","regular"],
    ["rconv19","regular"],
    ["rconv20","regular"],
  ],
  "p1_num_channels":48,
  "g1_num_channels":48,
  "v1_num_channels":48,
  "sbv2_num_channels":96,
  "num_scorebeliefs":8,
  "v2_size":112,
}


base_config_of_name = {
  "b2c16": b2c16,
  "b4c32": b4c32,
  "b6c96": b6c96,
  "b10c128": b10c128,
  "b15c192": b15c192,

  "b11c384llbt": b11c384llbt,

  "b20c256": b20c256,
  "b30c256bt": b30c256bt,
  "b24c320bt": b24c320bt,
  "b20c384bt": b20c384bt,
  "b23c256lbt": b23c256lbt,
  "b18c320lbt": b18c320lbt,
  "b15c384lbt": b15c384lbt,
  "b10c512lbt": b10c512lbt,
  "b12c384llbt": b12c384llbt,

  "b20c384lbt": b20c384lbt,

  "b30c320": b30c320,
  "b40c256": b40c256,
  "b40c384": b40c384,
  "b60c320": b60c320,

  "sandbox": sandbox,
}

config_of_name = {}
for name, base_config in base_config_of_name.items():
  config = base_config.copy()
  config["norm_kind"] = "fixup"
  config_of_name[name+""] = config

  config = base_config.copy()
  config["norm_kind"] = "bnorm"
  config_of_name[name+"-bn"] = config

  config = base_config.copy()
  config["norm_kind"] = "brenorm"
  config_of_name[name+"-brn"] = config


  config = base_config.copy()
  config["norm_kind"] = "fixup"
  config["use_attention_pool"] = True
  config_of_name[name+"-ap"] = config

  config = base_config.copy()
  config["norm_kind"] = "bnorm"
  config["use_attention_pool"] = True
  config_of_name[name+"-bn-ap"] = config

  config = base_config.copy()
  config["norm_kind"] = "brenorm"
  config["use_attention_pool"] = True
  config_of_name[name+"-brn-ap"] = config



